### ISSUE TITLE
Go should be preinstalled & configured

### ISSUE THREAD

**Issue by birmacher** [bitrise-docker/bitrise-base#1]
Go should be preinstalled and configured.

Now when I want to start a `go get` I get the following error:
`package (...): cannot download, $GOPATH not set. For more details see: go help gopath`

**Comment by viktorbenei** [comment]
Then create a PR :D

**Comment by viktorbenei** [comment]
Add it here https://github.com/bitrise-io/docker-bitrise-base/blob/master/Dockerfile#L65

**Comment by viktorbenei** [comment]
Fixed
