### ISSUE TITLE
Privileged docker execution for VPN capabilities

### ISSUE THREAD

**Issue by alleus** [bitrise-docker/bitrise-base#26]
I'm attempting to use bitrise.io by connecting to git servers behind a firewall. For this I'm utilizing a VPN connection (IPsec IKEv2). After som tweaking, I got this to work on the Mac OS stack, but I've come to a halt when implementing the same solution on the Android Ubuntu Docker stack.

The problem I have, is that the docker container is being run without the `--privileged` flag, witch means that the `CAP_NET_ADMIN` capability is disabled:

> "By removing CAP_NET_ADMIN for a container, the container processes cannot modify the systems network, meaning assigning IP addresses to network devices, setting up routing rules, modifying iptables." _[Source](https://opensource.com/business/14/9/security-for-docker)_

I've made a simple example script and done some experimenting on my own. I've set up a Google Cloud Compute Engine instance (Ubuntu 16.04) and installed Docker and the `bitriseio/docker-android` image. Connecting to the VPN directly from the VM shell works without problem, however, when running in the Docker image, starting the ipsec charon daemon is refused.

Sample script: [vpn.sh](https://gist.github.com/alleus/ef20144040116a2326afec12a02a4300)
Sample bitrise workflow: [bitrise.yml](https://gist.github.com/alleus/7c40d6c13638dc04bc6300ca9449c567)

All commands below are run as root.

### Starting from the VM shell
_To try out the kernel capabilities_

`$ ipsec start --nofork` [**Result**](https://gist.github.com/alleus/b673e9576f686922bae74c7fb2dfbd5a)

The charon daemon is [started successfully](https://gist.github.com/alleus/b673e9576f686922bae74c7fb2dfbd5a#file-vm-shell-log-L17)

### Starting from non-privileged Docker image
_This is how the bitrise.io VMs are run._

`$ docker run --env CI=false --volume "$(pwd):/bitrise/src" --rm bitriseio/docker-android:latest bitrise run primary` [**Result**](https://gist.github.com/alleus/ff0bc3bb754a59d6891ab3161fe9163d)

The charon daemon [can not be started](https://gist.github.com/alleus/ff0bc3bb754a59d6891ab3161fe9163d#file-non-privileged-log-L120) due to missing [`CAP_NET_ADMIN` capability](https://gist.github.com/alleus/ff0bc3bb754a59d6891ab3161fe9163d#file-non-privileged-log-L95)

### Starting from privileged Docker image
_This is what I'm after_

`$ docker run --env CI=false --privileged --volume "$(pwd):/bitrise/src" --rm bitriseio/docker-android:latest bitrise run primary ` [**Result**](https://gist.github.com/alleus/15b3dc5dcc55b82c2b0972c5332776ea)

The charon daemon is [started successfully](https://gist.github.com/alleus/15b3dc5dcc55b82c2b0972c5332776ea#file-privileged-log-L93)

### So...

Can you enable `--privileged` on the Docker image execution on your Android Ubuntu Docker stack, so we get the same capabilities as on your Mac OS stack? Since the VMs are created on demand, and discarded after the run, giving privileges to the scripts on the VM should be no implication on your infrastructure.

**Comment by viktorbenei** [comment]
Thanks for all the details @alleus !
We'll try to schedule this ASAP!

**Comment by viktorbenei** [comment]
Required bits implemented in https://github.com/bitrise-tools/bitrise-bridge/releases/tag/0.9.9 - now we just have to deploy it ;)

**Comment by alleus** [comment]
Sounds great! 👍 Looking forward to it!

**Comment by viktorbenei** [comment]
If everything goes as planned this should be available in this weekend's release ;)

**Comment by viktorbenei** [comment]
Deploy scheduled for tomorrow ;)

**Comment by viktorbenei** [comment]
Deployed!

I'll close this ticket, but if you'd have any issue, please comment here or create a new one!

And once again, thanks for all the info & your help! 😉 🚀 🎉
