### ISSUE TITLE
Unzip should be preinstalled

### ISSUE THREAD

**Issue by guitcastro** [bitrise-docker/bitrise-base#3]
OS X VM,  have unzip shipped installed in them. 

Others VM should have the unzip command as well, so steps like [Resource Archive](https://github.com/bitrise-io/steps-resource-archive) could be shared across platforms.

**Comment by viktorbenei** [comment]
I believe zip is installed on Ubuntu as well by default, which environment do you refer to?

**Comment by viktorbenei** [comment]
actually, just tested and `zip` is not available, good catch!

**Comment by viktorbenei** [comment]
PR merged, will be available later today on bitrise.io - probably in a couple of hours
