### ISSUE TITLE
install yarn by default.

### ISSUE THREAD

**Issue by chirag04** [bitrise-docker/bitrise-base#71]
yarn is an alternative(better?) to npm which is installed by default when install nodejs. Most CI systems now have yarn installed by default. 

While users can install yarn  using a script step, it would be nice if yarn was installed by default.

**Comment by viktorbenei** [comment]
I agree, but the main question with any new tool is, providing a single preinstalled version would be enough? In case of the Android/Linux stacks it's updated every week, but would that possibly break a project which used a version from one month ago? Or would that still work?

@chirag04 do you have any pointers for yarn compatibility "plan/schedule" docs?

**Comment by chirag04** [comment]
IMO new version should not break any project unlesss it's a major version bump. Yarn follows semver so expect same compatibility as any semver project

**Comment by bootstraponline** [comment]
yarn is awesome & used frequently with react-native projects. I'd also like to see it preinstalled someday.

**Comment by viktorbenei** [comment]
Feel free to send a PR to the provisioning repos https://github.com/bitrise-io/bitrise.io#request-a-tool-to-be-pre-installed-on-a-build-machine

**Comment by bootstraponline** [comment]
> Feel free to send a PR to the provisioning repos

done: https://github.com/bitrise-io/osx-box-bootstrap/pull/35

**Comment by bootstraponline** [comment]
& for linux: https://github.com/bitrise-docker/bitrise-base/pull/78

**Comment by viktorbenei** [comment]
PRs merged, yarn will be available after this weekend on the Linux/Android stack (the non LTS one), and on the Xcode Edge stack (and on new macOS/Xcode stacks, but not on existing ones, as explained at https://discuss.bitrise.io/t/how-are-the-bitrise-io-stacks-updated-and-with-what-frequency/281).

Thanks for everyone else supporting this request, and a huge thank you to @bootstraponline for submitting the PRs! 🎉 🚀
