### ISSUE TITLE
Cache always invalidated?

### ISSUE THREAD

**Issue by bootstraponline** [bitrise-docker/bitrise-base#76]
I ran `docker-compose build` successfully using the latest Docker (`Version 1.13.1-beta42 (15350)
`). Then on the second run, it built the entire image again from scratch. I'd expect it to use the cached images.

**Comment by bootstraponline** [comment]
I'm guessing this is a Docker for Mac issue. 😭

**Comment by viktorbenei** [comment]
>  I'd expect it to use the cached images.

Indeed that's what should happen. Did you try it inside a Linux VM, or on Linux directly?

**Comment by bootstraponline** [comment]
I only tried it on Docker for Mac 🍎.

**Comment by bootstraponline** [comment]
> Did you try it inside a Linux VM, or on Linux directly?

Works fine on VMWare Fusion using Ubuntu.

**Comment by bootstraponline** [comment]
fixed via https://github.com/bitrise-docker/bitrise-base/pull/79
