### ISSUE TITLE
docker-compose build failure

### ISSUE THREAD

**Issue by bootstraponline** [bitrise-docker/bitrise-base#77]
```
$  docker-compose --version
docker-compose version 1.11.1, build 7c5d5e4
```

```
$ docker --version
Docker version 1.13.1, build 092cba3
```

```
$ docker-compose build
Step 47/69 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y linux-image-extra-`uname -r`
 ---> Running in afec5ac57041
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package linux-image-extra-4.9.8-moby
E: Couldn't find any package by glob 'linux-image-extra-4.9.8-moby'
E: Couldn't find any package by regex 'linux-image-extra-4.9.8-moby'
ERROR: Service 'app' failed to build: The command '/bin/sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y linux-image-extra-`uname -r`' returned a non-zero code: 100
``

**Comment by viktorbenei** [comment]
You can't run that command in Docker for Mac unfortunately as AFAIK docker does not support the "alpine" linux which is used by Docker for Mac (in the background DfM uses a linux VM)

**Comment by viktorbenei** [comment]
What we usually do: use docker inside a full Virtual Machine, e.g. an Ubuntu one inside VirtualBox

**Comment by bootstraponline** [comment]
Oh, good to know. Maybe the readme should mention that Docker for Mac will have issues.

It did build successfully once, just not twice.

**Comment by viktorbenei** [comment]
> It did build successfully once, just not twice.

Really? That's strange. 

Btw you can run the image with Docker for Mac, you just can't build it with it (at least that was the case last time we tried it, but that was quite some time ago)

**Comment by bootstraponline** [comment]
I think if you tried it now, it will build. It's just flaky.

**Comment by viktorbenei** [comment]
Strange, because the error `linux-image-extra-4.9.8-moby` comes from `apt-get`, and it simply means that there is no package with the name `linux-image-extra-4.9.8-moby` available. (`moby` is the distribution name of the linux VM docker for mac uses in the background; e.g. in case of Ubuntu 16.04 this would be "xenial" which is the codename of Ubuntu 16.04 ("trusty" was Ubuntu 14.04, etc.))

**Comment by bootstraponline** [comment]
Yeah, that's weird. I tried it again and it's the same error. I don't know why `docker-compose build` ever worked on mac.
